### ISSUE TITLE
[request] add rss for your blog

### ISSUE THREAD

**Issue by Wsine** [andreas-zeller/andreas-zeller.github.io#1]
Dear Professor Zeller,

I am also a research student in SE and am very impressed with your blog posts. I wonder would you like to add an RSS feature to your blog so that I could easily follow whenever new posts are available. 

The setup is not so hard. just add two lines at your current configs. 
https://github.com/jekyll/jekyll-feed

appreciate it if you would like to do that.

Best,
Jankin

**Comment by andreas-zeller** [comment]
Done! Please check.
